// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"libraryDemo/user/cmd/rpc/internal/logic"
	"libraryDemo/user/cmd/rpc/internal/svc"
	"libraryDemo/user/cmd/rpc/userclient"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *userclient.IdReq) (*userclient.UserInfoReply, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
