// Code generated by goctl. DO NOT EDIT.
package types

type SearchReq struct {
	ID int64 `json:"id"; form:"id"`
}

type SearchRes struct {
	ID      int64  `json:"id"`
	UID     int64  `json:"uid"`
	BaseUrl string `json:"base_url"`
	Path    string `json:"path"`
}

type BatchReq struct {
	UID      int64  `json:"uid,optional"`
	MimeType string `json:"mime_type,optional"`
	Status   int64  `json:"status,optional"`
}

type BatchRes struct {
	ID      int64  `json:"id"`
	UID     int64  `json:"uid"`
	BaseUrl string `json:"base_url"`
	Path    string `json:"path"`
}
